task: nuswide         ## task name
batch_size: 400       ## batch size
code_length: 32       ## length of hashing vector
input_length: 2048    ## input length (corresponding to image extraction)
train_iter: 100000    ## training iteration
learning_rate: 0.0001 ## learning rate
continue_length: 512  ## length of continue vector